In [29]:
import ase
from ase.io import read, write
from ase.calculators.emt import EMT
import numpy as np

In [30]:
atom = ase.Atoms('N')
# write("POSCAR", atom, format="xyz")

In [31]:
atom.calc = EMT()
energy1 = atom.get_potential_energies()
energy1

array([5.1])

In [32]:
molecule = ase.Atoms('2N', [(0,0,0),(0,0,1.1)])
molecule.calc = EMT()
energy2 = molecule.get_potential_energies()
energy2

array([0.22017179, 0.22017179])

In [33]:
# N2的内能
2*(np.mean(energy2) - energy1)

array([-9.75965643])